require_relative '../soma'
require_relative 'channels'

task :default do
  channels = Channels.scrap
  soma = {
    'soma' => {
      'at' => Time.now,
      'channels' => channels
    }
  }
  Soma.save soma
end
